/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as MindScoreRouteImport } from './routes/mind-score'
import { Route as MelodyOfLifeRouteImport } from './routes/melody-of-life'
import { Route as MeditationRouteImport } from './routes/meditation'
import { Route as JournalNewRouteImport } from './routes/journal-new'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const MindScoreRoute = MindScoreRouteImport.update({
  id: '/mind-score',
  path: '/mind-score',
  getParentRoute: () => rootRouteImport,
} as any)
const MelodyOfLifeRoute = MelodyOfLifeRouteImport.update({
  id: '/melody-of-life',
  path: '/melody-of-life',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationRoute = MeditationRouteImport.update({
  id: '/meditation',
  path: '/meditation',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/journal-new',
  path: '/journal-new',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRoute
  '/journal': typeof JournalRoute
  '/journal-new': typeof JournalNewRoute
  '/meditation': typeof MeditationRoute
  '/melody-of-life': typeof MelodyOfLifeRoute
  '/mind-score': typeof MindScoreRoute
  '/mood': typeof MoodRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRoute
  '/journal': typeof JournalRoute
  '/journal-new': typeof JournalNewRoute
  '/meditation': typeof MeditationRoute
  '/melody-of-life': typeof MelodyOfLifeRoute
  '/mind-score': typeof MindScoreRoute
  '/mood': typeof MoodRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRoute
  '/journal': typeof JournalRoute
  '/journal-new': typeof JournalNewRoute
  '/meditation': typeof MeditationRoute
  '/melody-of-life': typeof MelodyOfLifeRoute
  '/mind-score': typeof MindScoreRoute
  '/mood': typeof MoodRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/games'
    | '/journal'
    | '/journal-new'
    | '/meditation'
    | '/melody-of-life'
    | '/mind-score'
    | '/mood'
    | '/pricing'
    | '/profile'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/games'
    | '/journal'
    | '/journal-new'
    | '/meditation'
    | '/melody-of-life'
    | '/mind-score'
    | '/mood'
    | '/pricing'
    | '/profile'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/games'
    | '/journal'
    | '/journal-new'
    | '/meditation'
    | '/melody-of-life'
    | '/mind-score'
    | '/mood'
    | '/pricing'
    | '/profile'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  CoachRoute: typeof CoachRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  GamesRoute: typeof GamesRoute
  JournalRoute: typeof JournalRoute
  JournalNewRoute: typeof JournalNewRoute
  MeditationRoute: typeof MeditationRoute
  MelodyOfLifeRoute: typeof MelodyOfLifeRoute
  MindScoreRoute: typeof MindScoreRoute
  MoodRoute: typeof MoodRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind-score': {
      id: '/mind-score'
      path: '/mind-score'
      fullPath: '/mind-score'
      preLoaderRoute: typeof MindScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melody-of-life': {
      id: '/melody-of-life'
      path: '/melody-of-life'
      fullPath: '/melody-of-life'
      preLoaderRoute: typeof MelodyOfLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditation': {
      id: '/meditation'
      path: '/meditation'
      fullPath: '/meditation'
      preLoaderRoute: typeof MeditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-new': {
      id: '/journal-new'
      path: '/journal-new'
      fullPath: '/journal-new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  CoachRoute: CoachRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  GamesRoute: GamesRoute,
  JournalRoute: JournalRoute,
  JournalNewRoute: JournalNewRoute,
  MeditationRoute: MeditationRoute,
  MelodyOfLifeRoute: MelodyOfLifeRoute,
  MindScoreRoute: MindScoreRoute,
  MoodRoute: MoodRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
